# Generated by Django 3.0.4 on 2020-03-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'InActive')], default='active', max_length=255),
        ),
    ]
