# Generated by Django 3.0.4 on 2020-03-30 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200330_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 30, 14, 37, 50, 358956, tzinfo=utc)),
        ),
    ]
